---
- hosts: ios
  gather_facts: no

  vars:
     names:
       - user1
       - user2

  tasks:
     - name: remove users
       ios_user:
         name: "{{ item }}"
         state: absent
         privilege: 15
       with_items: "{{ names }}"
       notify: save

  handlers:
     - name: save
       ios_config:
         save_when: modified
